### ISSUE TITLE
panic: zip: not a valid zip file

### ISSUE THREAD

**Issue by pomdtr** [progrium/go-vscode#1]
The content of `assets/vscode-web.zip` seems to be: 

```
version https://git-lfs.github.com/spec/v1
oid sha256:3dd2d91e5617ce158b0bfb5010f748d3ffe865a884b6dbd818127f59cf975cd1
size 17485506
```

You probably want to disable git lfs for it

**Comment by pomdtr** [comment]
Here is the commit erroring out if you need a repro

**Comment by progrium** [comment]
I'm trying to figure out a good way to include this zip file without actually versioning a 18 MB binary. I thought git lfs might work for Go libraries, but looks like not. Any ideas? In the meantime, if you pull again, you can use make to pull the zip file. I'd really like to avoid introducing `go generate` for this.

**Comment by pomdtr** [comment]
One way would to host the assets elsewhere (ex: published a npm package, and accessed from jsdelivr), and then only embed a minimal index.html page in the go binary.

**Comment by progrium** [comment]
Sounds like you're saying download it at runtime. It can't be in index.html because its used in Go, embedded at compile time. The problem is it would have to be stored/cached somewhere, on top of making an "unexpected" request in the first place. I'd really like it to just be embedded, but open to alternatives if there's nothing else.

**Comment by pomdtr** [comment]
The request would be done by the end-user browser, at runtime.

Instead of fetching assets from your server, it would fetch them from a public CDN.

**Comment by progrium** [comment]
I see. Since we are mostly just serving them as static files, they could be served by a CDN. It seems like an unnecessary dependency on something else I'd have to maintain. Maybe if we did something like this, but if you run `go generate` it will download it and embed it at compile time, only using the CDN if it hasn't been embedded... hmm

**Comment by progrium** [comment]
Alternatively, though, I sort of like the idea of downloading the zip at runtime in Go instead of the CDN option if you also have the `go generate` option to avoid this.

**Comment by progrium** [comment]
Ok, I'll try this and see how it goes.

**Comment by pomdtr** [comment]
One other alternative would be to just not distribute vscode, and instead just connect to the vscode instance of the user using an extension url:

1. The user access your website.
2. The website redirect the user to an `vscode://` uri
3. The user get prompted to install your extension
4. The extension get installed, and the remote file system get opened on your local vscode

**Comment by progrium** [comment]
Yes there are a handful of configurations and this is just one. The focus here is on having your own embedded/custom version of VSCode, so if you want to just launch VSCode you can just ... do that.

**Comment by pomdtr** [comment]
The benefit I see is that you would be able to wire VS Code to any filesystem implementing the `FS` interface.

**Comment by progrium** [comment]
Tried a bunch of stuff that didn't work. For now, going to continue using Git LFS, but I added this note on how to make it work: https://github.com/progrium/go-vscode#requires-git-lfs
